### PR TITLE
Test against mysql,pgsql and sqlite

### PR DESCRIPTION
**Pull request by Baachi**

### CODE REVIEW

**Comment by Baachi** [comment]
Seems that this library isn't compatible with PostgreSQL.

**Comment by henrikbjorn** [comment]
Cool.

Is it possible to not run theese in a normal development cycle? and have them be enable for travis or via some group (not sure how phpunit handles this)

**Comment by Baachi** [comment]
Currently no idea, but i will investigate and let you know.

**Comment by henrikbjorn** [comment]
THanks for your work on this! :)

**Pull request merged**
