### PR TITLE
This is another unnecessary condition

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by henrikbjorn** [comment]
This is not unnecessary, it is a guard and makes the code cleaner to look at IMO

**Comment by sagikazarmark** [comment]
Then it is inconsistent with the InMemoryQueue. Also, I don't think it is cleaner to read:

1. If the queue does not exists do nothing, otherwise do something else.
2. If the queue exists do this

I think the second one is much cleaner.

**Comment by henrikbjorn** [comment]
I like the first one :) and would rather have the InMemoryFactory respect the same convention.

**Comment by sagikazarmark** [comment]
Not to mention it is much harder to test. But I leave it then.

**Pull request closed without merging**
