### PR TITLE
AWS SQS FIFO Queue support

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/bernardphp/bernard/issues/317

### CODE REVIEW

**Comment by martinssipenko** [comment]
Two things:
1) missing test
2) I don't think it's good to assume that FIFO queues will always have `.fifo` suffix. Perhaps it would be better to implement a new FIFO driver?

**Comment by holtkamp** [comment]
>missing test

will have a look on how to test this

>I don't think it's good to assume that FIFO queues will always have .fifo suffix. Perhaps it would be better to implement a new FIFO driver?

Well, for SQSDriver that "is" the case, right?
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html

>"The name of a FIFO queue must end with the .fifo suffix. The suffix counts towards the 80-character queue name limit. To determine whether a queue is FIFO, you can check whether the queue name ends with the suffix."

**Comment by martinssipenko** [comment]
OK, wasn't aware that suffix is a requirement from AWS, in that case it should be ok.

**Comment by rdohms** [comment]
How is the progress on this?

**Comment by holtkamp** [comment]
Failed travis tests seem unrelated. Have been using this in production since mid-July now... Guess its waiting for approval by (busy) library maintainers...

**Comment by acrobat** [comment]
Changes look good to me, I'm just waiting for a review from @sagikazarmark before merge. Sorry for the deplay!

**Comment by rdohms** [comment]
Awesome, it would be amazing if we get a release somewhere this week with this, would make my team a very happy team :D

**Comment by acrobat** [comment]
Even though I'm on vacation, let's make your team happy @rdohms :smile:. A new release should be available shortly after the merge!

**Comment by acrobat** [comment]
@rdohms @holtkamp new release with this PR included: https://github.com/bernardphp/bernard/releases/tag/v1.0.0-alpha6

**Pull request merged**
