### PR TITLE
Composer > Require phpunit in dev

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by henrikbjorn** [comment]
This have been suggested quite a few times. phpunit is a tool and not a dependency. Sorry.

**Comment by ruudk** [comment]
Can we remove it here too: https://github.com/bernardphp/BernardBundle/blob/master/composer.json#L20 

The reason for this, is that in order to test the bernard package, one has to install phpunit themself

**Comment by mathewpeterson** [comment]
@henrikbjorn Can you explain what you mean by "phpunit is a tool and not a dependency" because my interpretation is that it _is_ a development dependency and thus be included in the `composer.json`.

**Comment by mpdude** [comment]
If PhpUnit is a tool and not a dependency, what is a "devDependency" then?

**Comment by henrikbjorn** [comment]
@ruudk yes we can.

**Comment by ruudk** [comment]
@henrikbjorn I just wanted to point out the inconsistency ;)

**Comment by mathewpeterson** [comment]
I'm not sure I'm following what's going on here.

Why is this not getting added in?

**Comment by ruudk** [comment]
I don't get it either. What would happen if I was using a PHPUnit version locally that didn't work with some of the features in Bernard? 

Normally I can just run `composer install` when creating new features and run it with the vendor/phpunit installed in the project....

**Comment by mathewpeterson** [comment]
There are unit tests written with PHPUnit therefore PHPUnit is a dependency.

**Comment by henrikbjorn** [comment]
@mathewpeterson it is a tool AND a dependency, the phpunit package isnt small ~15 additonal packages to install.

Also i share the same view as fabpot does in this comment https://github.com/symfony/symfony/pull/5748#issuecomment-9515759

**Comment by mathewpeterson** [comment]
@henrikbjorn What does the size of the package have to do with any of this? It will only get installed in the other packages. If you're not satisfied with PHPUnit then use something else and remove the dependency. 

This is really a silly argument.

**Comment by davidsteinsland** [comment]
Agree on the aforementioned comments: phpunit is a tool, yes, but it is also a *development dependency*. When contributing to a project, I'd like to just run `./vendor/bin/phpunit`. Now I had to visit a Travis build to check which version was used, and install it anyways.

Most people have phpunit cached in their composer also, so installation is a matter of seconds.

This is the whole point why composer has `--no-dev` flag: there may be countless development dependencies for a project, but only a few production dependencies. I can expect that my production environment should need some configuration (installation of packages, libraries, etc), but a development environment should be homogeneous.

**Comment by henrikbjorn** [comment]
As much as you guys think my argument is silly, that is still what i think. And you haven't specified any compelling reason why, you just cant install it globally. Also none have specified any BC breaks in phpunit 3, 4 or 5 that makes the test suite inconsistent.

**Comment by davidsteinsland** [comment]
Bernard test suites contains `willReturn()` instead of `$this->will($this->returnValue())` which is not supported in phpunit 3.x.

**Pull request closed without merging**
