### PR TITLE
Move Beanstalk driver to new namespace

### PR DESCRIPTION
**Pull request by namoscato**
See #256.

### CODE REVIEW

**Comment by reinfi** [comment]
Eigentlich ist der Namespace falsch, denn die Queue heißt Beanstalkd.

**Comment by namoscato** [comment]
Cool, yeah happy to change that. Another option I considered is a more specific `Pheanstalk` namespace.

**Comment by acrobat** [comment]
With our current requirement of the "pda/pheanstalk" lib, a `pheanstalk` namespace would be more correct imo

What do you think @sagikazarmark?

**Comment by sagikazarmark** [comment]
I don't mind either way. The current name is pheanstalk, so sticking to it probably makes the transition easier for others.

Also, thanks for your outstanding work @namoscato , sorry I haven't responded earlier. I will try to review your PRs before the end of the year, that's the best I can promise at the moment.

**Comment by acrobat** [comment]
I will also try to go through all pr's and submit a review. Hopefully this will make it easier to merge (or atleast quicker)

**Comment by sagikazarmark** [comment]
@namoscato thanks a lot, outstanding work!

**Pull request merged**
