### PR TITLE
Docs rewrite

### PR DESCRIPTION
**Pull request by acrobat**
I've started on the rewrite of the docs to get this library ready for a stable release. All feedback is welcome and I will list the things that are still left to fix/document in the PR

I have also created a temporary readthedocs page to see the changes in the actual template: https://bernard-fork.readthedocs.org/en/docs_rewrite/ (these pages are private so they will not cause confusing the the real docs and will be deleted when this PR is merged)

TODO:

- [x] Move queue docs from producing to separate queue page (inMemory, persistent, roundrobin)
- [ ] Serializers

### CODE REVIEW

**Comment by acrobat** [comment]
@henrikbjorn this PR is ready for a review! I think most of the docs are up to date with the latest code. I oly need so help with the serializer part

**Comment by henrikbjorn** [comment]
Looks good!

**Comment by acrobat** [comment]
Rebased branch and squashed commits. @henrikbjorn can we merge this PR and finish the serializer docs in another pr?

This will improve the docs so new users who use the master or latest alpha release will have mostly correct docs!

**Comment by henrikbjorn** [comment]
@acrobat Thanks a lot for your work on this!

**Comment by acrobat** [comment]
No problem! Builds seem to be [failing ](http://readthedocs.org/projects/bernard/builds/)

Will try to check later today what the exact problem is!

**Pull request merged**
