### PR TITLE
Amazon SQS automatic queue creation

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/bernardphp/bernard/pull/295#issuecomment-316026902

### CODE REVIEW

**Comment by acrobat** [comment]
@holtkamp can you rebase onto the current master?

**Comment by holtkamp** [comment]
@acrobat yeah, tried it locally, did not work out 😞 , GitHub allowed to resolve the conflicts, is it ok now?

**Comment by holtkamp** [comment]
Mmm, sorry for this mess, guess I have to start from scratch to create a clean PR

**Comment by holtkamp** [comment]
@acrobat sorry for the confusion, it seems to be mergeable now. You can squash commits using GitHub interface I suppose?

**Comment by acrobat** [comment]
Changes look good to me. @holtkamp is it possible to add a test for this?

**Comment by holtkamp** [comment]
Well, I stared at it for some time, but really got no clue how to test this... Suggestions? The whole mocking stuff is kind of new for me... 😥

**Comment by acrobat** [comment]
I will think about it (maybe implement a test for this when moving the drivers to a separate repo). But for now let's just merge it!

**Comment by acrobat** [comment]
Thanks @holtkamp!

**Comment by sagikazarmark** [comment]
Please try to avoid having merge commits like this: `Merge branch 'master' of...`

If you still do end up having one, please use the squash feature of Github merge.

**Comment by sagikazarmark** [comment]
I will try to setup an amazon account for integration tests.

**Comment by acrobat** [comment]
Yeah rebasing a branch is better but no big issue as it indeed can be merged with the squash feature of github (as was done with the merge https://github.com/bernardphp/bernard/commit/28e5b261d5566ac57e40758ad9ec4f6b98b3d467)

**Comment by holtkamp** [comment]
aah, great, thanks guys. Yeah my GIT skills are still quite basic. Rebasing seemed to fail so I relied on the "squash commits" feature when merging... 

Any plans for a newly tagged release? 😇

**Comment by sagikazarmark** [comment]
> Any plans for a newly tagged release?

Sorry, no plans in the near future. Things will break in the near future, so I don't see any point in releasing now.

**Comment by holtkamp** [comment]
and a bumped alpha release like `1.0.0-alpha7`, just to point our `composer.json` to in order to incorporate the improved SQS functionality?

**Comment by holtkamp** [comment]
> Things will break in the near future, so I don't see any point in releasing now.

Would you consider my "point" to do tag a new minor release: functionality was added?

**Comment by acrobat** [comment]
@sagikazarmark what do you think, have a last alpha release with these (and some other) fixes and after that focus on work for stable 1.0.0, with possible breaking changes?

**Comment by sagikazarmark** [comment]
Since we are not working towards 1.0 with these "alpha" releases, I don't see any point in them as alpha releases of 1.0. We can of course tag releases, but I think that's a huge mistake from versioning point of view. Not to mention how fragile it is to rely on alpha versions.

If I were you, I would rather maintain a custom version of the driver until 1.0 is tagged.

That's my opinion on the matter. That being said, alpha releases are already kinda abused, so it won't really hurt more than it already does. Feel free to tag an alpha release @acrobat.

**Comment by acrobat** [comment]
Ok, I will try to do it in the next days!

**Comment by acrobat** [comment]
@holtkamp I've just released a new alpha with these changes included. See https://github.com/bernardphp/bernard/releases/tag/v1.0.0-alpha7

/cc @sagikazarmark

**Pull request merged**
