### PR TITLE
Added support for the mongodb-php-library/extension combo

### PR DESCRIPTION
**Pull request by mkherlakian**
The ext-mongo has been replaced by the mongodb-php-library/extension driver - this PR adds support for it.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@mkherlakian thanks a lot for the contribution. Would you be open to moving this PR to https://github.com/bernardphp/drivers ?

**Comment by mkherlakian** [comment]
@sagikazarmark Absolutely. I wasn't sure if the project was being maintained since the PR was initiated over a year ago. I'll work on it as soon as I have a moment.

**Comment by mkherlakian** [comment]
Is the above repo that you mention the future direction for drivers for the project, meaning that the Driver/ folder will disappear from this one?

**Comment by sagikazarmark** [comment]
It won't disappear entirely, the flat file driver for example will remain here. We are moving out drivers with external dependencies.

Unfortunately we didn't have much time lately, but I try to review open PRs and issues from time to time.

**Pull request closed without merging**
