### PR TITLE
hardcoded queue prefix as constant

### PR DESCRIPTION
**Pull request by bashilbers**
So you can extract the queue prefix for manual operations (so I don't have to inject a Driver and Producer in a component that actually produces and wants to do ->countMessages())

### CODE REVIEW

**Comment by acrobat** [comment]
Thanks @bashilbers!

**Comment by sagikazarmark** [comment]
Not good, merge freeze please until I sort the driver PR out. Now it's conflicting. :(

**Comment by acrobat** [comment]
Oh damn, I forgot about that! Sorry, I will wait with merges until further notice!

**Comment by sagikazarmark** [comment]
Np, thanks. I will try to sort it out ASAP, but requires a lot of review to make sure nothing is screwed up.

**Comment by acrobat** [comment]
Yes I understand! If you need any help, just let me know!

**Pull request merged**
