### PR TITLE
Use Assertion to make sure arguments are present

### PR DESCRIPTION
**Pull request by henrikbjorn**
maybe use assertion library

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@henrikbjorn I made some modifications to your branch.

https://github.com/sagikazarmark/bernard/tree/assert

Should I open another PR for it?

**Comment by sagikazarmark** [comment]
Also, can `Verify` class be removed? I modified that also, so it now uses `Assertion`. But I couldn't find any use cases for it. So I think It just can be removed.

**Comment by henrikbjorn** [comment]
yeah please open a PR :) if we cover all with this library the Verify class should be removed.

**Comment by sagikazarmark** [comment]
As I said, I cannot find any uses of `Verify` in the library.

**Comment by henrikbjorn** [comment]
Then it should just be removed.

**Comment by henrikbjorn** [comment]
Maybe it could be simplified even more, there is a allNotEmpty that might be of use.

**Comment by sagikazarmark** [comment]
I am not sure that provides the functionality you think.

**Comment by henrikbjorn** [comment]
There is also a allNotEmptyKey :)

**Comment by sagikazarmark** [comment]
I think it's syntax is allNotEmptyKey(array(array(), array()), 'key').

**Comment by sagikazarmark** [comment]
Found the solution: `choicesNotEmpty`. Implemented it in the PR.

**Pull request closed without merging**
