### PR TITLE
Minimum php version

### PR DESCRIPTION
**Pull request by sagikazarmark**
Whenever you think it's time... ;)

### CODE REVIEW

**Comment by Baachi** [comment]
:heart:

**Comment by henrikbjorn** [comment]
i think that the master changes a lot of things already, then it would be okay. Also since ubuntu 14.04 is almost a year old and it ships with 5.5.

Would you add testing for 7.0 aswell ? the composer constraint woulld be `~5.4 || ~7.0` to allow it, and then add as the others to the travis file.

**Comment by sagikazarmark** [comment]
What's the problem with `>=5.4` version constraint?

**Comment by Baachi** [comment]
Seem the redis php extension isn't PHP 7 compatible.

**Comment by henrikbjorn** [comment]
@sagikazarmark the >= defines a broad range. where ~5.4 allows only >=5.4,<6.0. with the `||` ~7.0 it allows >=7.0,<8.0

**Comment by henrikbjorn** [comment]
we should do a travis.sh script in the test folder, or something. So it is easier to maintain the conditionals.

**Comment by sagikazarmark** [comment]
Shouldn't we allow failure of PHP 7 builds?

**Comment by henrikbjorn** [comment]
We should, and check why it thinks our json is invalid.

**Comment by sagikazarmark** [comment]
Hm..probably a null or empty string is not valid in PHP 7?

**Comment by henrikbjorn** [comment]
@sagikazarmark can you check? ill happily merge this after.

**Comment by sagikazarmark** [comment]
Yeah, will look at it in a few hours.

**Comment by sagikazarmark** [comment]
@henrikbjorn I don't know what causes the problem. I downloaded [this](https://atlas.hashicorp.com/rasmus/boxes/php7dev) php Vagrant build and tests run just fine. (But I am not sure about its revision)

Apart from that only the phpunit version might be different in the two environments, but I don't know how that could have an effect on this error. (Update: just checked it, my local and the travis phpunit versions are both 4.5)

My suggestion to "workaround" (aka. prevent the error from occuring):

``` php
    /**
     * {@inheritDoc}
     */
    public function execute(InputInterface $input, OutputInterface $output)
    {
        $name    = $input->getArgument('name');
        $queue   = $input->getOption('queue');
        $message = [];

        if ($input->hasArgument('message')) {
            $message = json_decode($input->getArgument('message'), true);

            if (json_last_error()) {
                throw new \RuntimeException('Could not decode invalid JSON [' . json_last_error() . ']');
            }
        }

        $this->producer->produce(new DefaultMessage($name, $message), $queue);
    }
```

**Comment by sagikazarmark** [comment]
Damn, realized it won't work.

**Comment by sagikazarmark** [comment]
Found a way, take a look at it

**Comment by henrikbjorn** [comment]
Thanks for your work on this!

**Pull request merged**
