### PR TITLE
Implement createQueue() and removeQueue()

### PR DESCRIPTION
**Pull request by holtkamp**
had a look at ways to test this, but can not figure out how in [SqsDriverTest](https://github.com/bernardphp/bernard/blob/7949ba87a1c58f8dd4c17120f4f24acd4df764e3/tests/Driver/SqsDriverTest.php)...

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Add it to the mockbuilder and verify it is called with the right arguments.

**Comment by holtkamp** [comment]
Thanks for the hint, this is new for me. 

trying this:

```php
    public function testCreatesQueue()
    {
        $this->sqs
            ->expects($this->once())
            ->method('createQueue')
            ->with($this->equalTo(['QueueName' => self::DUMMY_QUEUE_NAME]));

        $this->driver->createQueue(self::DUMMY_QUEUE_NAME);
    }
```

results in 

```
➜  bernard git:(patch-sqs-driver) ✗ php vendor/bin/phpunit
PHPUnit 4.8.31 by Sebastian Bergmann and contributors.

.........................................SSSSSSSSSS............  63 / 173 ( 36%)
...SSSSSSSS...........E........................................ 126 / 173 ( 72%)
...............................................

Time: 1.25 seconds, Memory: 12.00MB

There was 1 error:

1) Bernard\Tests\Driver\SqsDriverTest::testCreatesQueue
InvalidArgumentException: Operation not found: CreateQueue

/Users/user/workspace/bernard/vendor/aws/aws-sdk-php/src/AwsClient.php:208
/Users/user/workspace/bernard/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:78
/Users/user/workspace/bernard/src/Driver/SqsDriver.php:63
/Users/user/workspace/bernard/tests/Driver/SqsDriverTest.php:52

FAILURES!
Tests: 173, Assertions: 287, Errors: 1, Skipped: 18.
```

Note the AwsClient uses ```__call``` magic, maybe that is not supported by this approach of testing?

**Comment by henrikbjorn** [comment]
You need to add it to the stubbed methods here https://github.com/bernardphp/bernard/blob/7949ba87a1c58f8dd4c17120f4f24acd4df764e3/tests/Driver/SqsDriverTest.php#L19

**Comment by holtkamp** [comment]
@henrikbjorn ok, think I got the idea now. Have not squashed the commits: GitHub now allows to do that quite easily when accepting a PR...

**Comment by holtkamp** [comment]
@henrikbjorn anything missing for this to be merged?

**Pull request merged**
