### PR TITLE
Support Symfony 3.0

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by henrikbjorn** [comment]
THanks ;)

**Comment by ruudk** [comment]
It is possible to tag a release?

**Comment by ruudk** [comment]
We use https://github.com/bernardphp/bernard/tree/1.0.0-alpha1 in production for a month now without problems. So how bout a 1.0.0 release ;)

**Comment by henrikbjorn** [comment]
nice to hear. because of the issues the last couple of days i tagged a alpha2 release

**Pull request merged**
