### PR TITLE
ensure index is used when querying

### PR DESCRIPTION
**Pull request by bendavies**
The doctrine driver isn't using the [index](https://github.com/bernardphp/bernard/blob/master/src/Doctrine/MessagesSchema.php#L54) when querying for messages. (This is noticable when you queue up 200k message)

First i tried modifying the index, but whatever I tried, I couldn't make postgres use an index for the current queries.
So i'm removing the secondary order on id. This library does not guarantee ordered message delivery, so i think this is fine.

Tests don't pass because of this change. how would you like to address that?

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Can we fix this by adding an index, that uses both field?

**Comment by bendavies** [comment]
@henrikbjorn i said that i tried and failed. but really, why does it order by ID anyway?

**Comment by henrikbjorn** [comment]
Then we should just fix the tests.

**Comment by bendavies** [comment]
yes, again, i asked in my first message how you would like to go about that. I'll 
do the simplest fix for now.
It seems to me that the ordering by ID was specifically there to make the tests pass.

**Comment by bendavies** [comment]
@henrikbjorn passing now. small sleep in the unit test to force a different timestamp

**Comment by bendavies** [comment]
@henrikbjorn is this good for merge?

**Comment by henrikbjorn** [comment]
Instead of sleep can we peek 3 messages at a time and verify they are part of that array? Same with pop(), just pop 3 times and check the messages popped is part of the array.

**Comment by bendavies** [comment]
@henrikbjorn like that?

**Pull request merged**
