### PR TITLE
Do not resolve URL when creating a Queue, to prevent exceptions to be thrown

### PR DESCRIPTION
**Pull request by holtkamp**
As described here https://github.com/bernardphp/bernard/issues/294

### CODE REVIEW

**Comment by holtkamp** [comment]
This probably need some tests? @martinssipenko, you submitted https://github.com/bernardphp/bernard/pull/289, was there any particular reason to use a different type of exception [than was used in the the method signature](https://github.com/bernardphp/bernard/blob/a731681e29b6b67defa366ff9c071a3aa05bab16/src/Driver/SqsDriver.php#L185)?

**Comment by martinssipenko** [comment]
The reason why I used `\InvalidArgumentException` was because that's what is thrown by `SqsDriver::resolveUrl`. I see that there indeed is a bug, when the queue does not exist AWS SDK will throw `SqsException`, however I don't think `SqsExceptions` should be thrown where you suggested.

Instead I'd wrap `$result = $this->sqs->getQueueUrl(['QueueName' => $queueName]);` in try/catch and catch `SqsException` ([somewhere around line 93](https://github.com/bernardphp/bernard/pull/295/files#diff-f85541faed3678e887ffdee2a1217900R193)).

```php
try {
    $result = $this->sqs->getQueueUrl(['QueueName' => $queueName]);
} catch (SqsException $e) {
    throw new \InvalidArgumentException('msg', 0, $e);
}
```

**Comment by holtkamp** [comment]
>Perhaps the createQueue simply should not use resolveUrl

Yeah, kind of leaning towards that angle as well...

**Comment by holtkamp** [comment]
@martinssipenko shall we wrap this up? How to continue?

**Comment by martinssipenko** [comment]
I think swallowing an exception is a bad idea. I'd go with my initial proposal that does not use resolveUrl

**Comment by holtkamp** [comment]
>I'd go with my initial proposal that does not use resolveUrl

Ok, tried to do a clean rebase but that seems to have failed. Maybe GitHub offers a Squash Commits and merge of the PR?

**Comment by martinssipenko** [comment]
This is out of scope of the initial PR. Can you change the description to reflect actual changes?

**Comment by holtkamp** [comment]
Done, not sure this description *does* cover it 😉, feel free to change as you see fit.

**Comment by martinssipenko** [comment]
Looks good, apart from the rebase stuff and failing tests. Maybe you can open a new PR instead of this one?

**Comment by holtkamp** [comment]
>Maybe you can open a new PR instead of this one?

Yeah, might be better. Would you consider merging https://github.com/bernardphp/bernard/pull/318  first to prevent potential merge conflicts?

**Comment by martinssipenko** [comment]
I'm unable to merge @henrikbjorn potentially could help.

**Comment by holtkamp** [comment]
Note that when going down this road, automatic creation of queues when they do not exist will not work. 😞

**Pull request closed without merging**
