### PR TITLE
[WIP] Phpspec

### PR DESCRIPTION
**Pull request by sagikazarmark**
Merges in specs by @henrikbjorn. Adds new specs.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@henrikbjorn I started to work on spec tests. Do you want phpunit to be fully exchanged with phpspec? I start to cross-check the new spec tests and the unit tests so far. If you want to remove phpunit, I will remove the specific unit tests when they are completely replaced with spec tests.

**Comment by henrikbjorn** [comment]
It would be great to exhange them were possible and instead add behat (at some time) to cover the functional tests

**Comment by sagikazarmark** [comment]
I decided to stop developing this, because we have been talking about a possible separation of the drivers from the core. When that happens, this PR can be finished (there are only a few uncovered parts) and optionally behat can be added for functional tests.

@henrikbjorn Opinion?

**Comment by sagikazarmark** [comment]
BTW, I would be happy to help breaking the main repo into several pieces.

**Comment by sagikazarmark** [comment]
This needs to be reworked.

**Pull request closed without merging**
