### PR TITLE
Added docs readme and build script

### PR DESCRIPTION
**Pull request by acrobat**
I've started on the rewrite of the docs for the 1.0.0 stable release, so i've added a build script to build the docs easily on a local machine. And also a readme so people know how to build the docs themself

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Merging this made the readthedocs build fail. 

```
Could not open requirements file: [Errno 2] No such file or directory: 'doc/requirements.txt'
```

**Comment by acrobat** [comment]
Hmm, will check it and send PR with a fix!

**Comment by acrobat** [comment]
Hmm, will check it and send PR with a fix!

Strange thing is that the error triggers on the 1.0.0-alpha2 tag (50bc6260)

**Comment by acrobat** [comment]
@henrikbjorn I don't think the failure is related to this change, I triggered the docs builds [manually here](http://readthedocs.org/projects/bernard/builds/). But the stable docs haven't been build for some time, so can't really check where it gone wrong. But master doc's still build correctly so I guess we can ignore this for now and just check, when a stable version is tagged, if this docs still fail

**Pull request merged**
