### PR TITLE
Use queue name when fetching queue instance instead of message name.

### PR DESCRIPTION
**Pull request by robinvdvleuten**
This seems to fix issue #198 for me. By using the _getQueue_ method of a _Message_ instance I get the correct index name of the queue.

### CODE REVIEW

**Comment by elazar** [comment]
This would break any existing custom `Message` implementations by adding a new method they must implement. While I don't like the coupling this alternate option would introduce, the calls within `RoundRobinQueue` could be changed to `$envelope->getMessage()->getQueue()` without breaking API compatibility.

**Comment by robinvdvleuten** [comment]
@elazar Is calling `$envelope->getMessage()->getQueue()` not the same as my solution? If `getMessage()` returns a `Message` interface, you still need to make sure that it has the `getQueue()` method somehow.

**Comment by henrikbjorn** [comment]
This changes the interface and cannot be merged.

Id rather pull out the RoundRobin stuff and have it be reworked.

@robinvdvleuten are you relying on master?

**Comment by robinvdvleuten** [comment]
@henrikbjorn yes I'm currently using the 1.0.x-dev alias in composer

**Pull request closed without merging**
