### PR TITLE
Feature/ping event

### PR DESCRIPTION
**Pull request by Baachi**
Hey!

i created a event listener which checks the database connection before the message is processed. This is helpfull, so mysql doesn't close the connection if you process
a time consuming message e.g. API Requests and so on.

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Seems nice. The CI fail is proberly because of something else?

**Comment by Baachi** [comment]
Not sure if the errors are related to my PR. It rather seems, phpunit and phpspec seems to have a problem with `COMPOSER_OPTS="--prefer-lowest"`.

**Comment by henrikbjorn** [comment]
@Baachi would you mind rebasing and rerunning the tests?

**Comment by henrikbjorn** [comment]
Thanks for your work on this :)

**Pull request merged**
