### PR TITLE
Increase compatibility with Symfony 4.3 by using proper order of parameters

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/bernardphp/bernard/issues/404

### CODE REVIEW

**Comment by acrobat** [comment]
Thanks @holtkamp!

**Comment by holtkamp** [comment]
Thanks @acrobat!

Would this justify tagging a new PATCH version `0.13.1`?

**Comment by holtkamp** [comment]
@acrobat would it be possible to tag a new patch release which includes this PR?

**Comment by acrobat** [comment]
@holtkamp sorry I've must have missed that first comment! I will look into tagging a new release later today!

**Comment by acrobat** [comment]
@sagikazarmark I see that there a quite a lot changes done [on master](https://github.com/bernardphp/bernard/compare/1.0.0-alpha9...master). I'm not up to date on the state of the master branch, can I tag a new alpha release or is there more work to be done before a release?

**Pull request merged**
